### ISSUE TITLE
info_teleport_destination

### ISSUE THREAD

**Issue by maXusIprime** [fluffyst/Surftimer#10]
Hey just wanted to ask if there is a way to teleport to the destinations that are build in the maps and are also inside a zone so you teleport to the destination instead of just the middle of the zone. 
Sry for bad english :/

**Comment by fluffyst** [comment]
Hi, this feature is possible to add but is not supported currently, I won't be adding new features anytime soon though, sorry.

**Comment by fluffyst** [comment]
This has now been added since v2.0.1
