### ISSUE TITLE
Style Low-Grav doesn't work

### ISSUE THREAD

**Issue by DuskTheAbhorrent** [fluffyst/Surftimer#107]
Hi can't seem to get this to work no matter what I tweak both in source/configs/.sp's switching to this style results in just nothing changing. It's the same as default/normal. Other styles work fine.

Thank you for your time,
Mike

**Comment by DuskTheAbhorrent** [comment]
Never mind it was a parachute plugin causing this.

**Comment by LubricantJam** [comment]
Why would you have parachute on surf...
