### ISSUE TITLE
Warnings on recompile + adding new styles?

### ISSUE THREAD

**Issue by DuskTheAbhorrent** [fluffyst/Surftimer#108]
// surftimer/misc.sp(1273) : warning 204: symbol is assigned a value that is never used: "speed"
// surftimer/misc.sp(1948) : warning 204: symbol is assigned a value that is never used: "buffer"
// surftimer.sp(1) : warning 203: symbol is never used: "disableServerHibernate"
// surftimer.sp(558) : warning 203: symbol is never used: "g_rankNameChatColour"
// surftimer.sp(14) : warning 203: symbol is never used: "revertServerHibernateSettings"

What's the dealio with these? 

Other issue, I've been trying to add new styles but the further I dig into them the less cohesive it seems there's little bits here and there across 2-4 files afaik and even after carefully considering and adding to all those I still run into issues. After a few hours troubleshooting I was finally shut down in game after selecting new style in the sense that rank/hudtimer disappeared and throwing I believe out of bounds "index error > 6"

I'm fairly new to SourcePawn with a Java/Python background which means more or less fuck all here besides the basics/syntax. Can anybody suggest a cohesive solution to adding more styles? I would imagine making a new file like scripting/surftimer/extrastyles.sp would be ideal here but it looks like too much is hard coded in all over the place as warned in the README.md

Some examples or even a point in the right direction would be wonderful at this point I'm like a blind man wandering around a crowded forest in another country at the moment.

Thank you for your time,
Dusk

**Comment by fluffyst** [comment]
warnings are just stuff i haven't bothered to fix and as a reminder for me to go back and look @ them u can ignore them or fix them urself if u want.

styles is a complete utter mess, it was the first thing I ever did learning sourcepawn so........ yeah lol it's a big disaster trying to add more it's all heavily hard coded.

i haven't really bothered to fix it because unlike bhop, most surfers don't really care about styles, pretty sure out of all the time the server has been up you're the first person to request to add more styles, maybe I'll re-write it in the future idk

if you want advice i think i commented everything with like // styles or something lol, but basically you probably need to up the array size for almost all the style variables or the max_styles variable and just do the same thing as the other styles but yeah gl

**Comment by DuskTheAbhorrent** [comment]
> warnings are just stuff i haven't bothered to fix and as a reminder for me to go back and look @ them u can ignore them or fix them urself if u want.
> 
> styles is a complete utter mess, it was the first thing I ever did learning sourcepawn so........ yeah lol it's a big disaster trying to add more it's all heavily hard coded.
> 
> i haven't really bothered to fix it because unlike bhop, most surfers don't really care about styles, pretty sure out of all the time the github has been up you're the first person to request to add more styles, maybe I'll re-write it in the future idk
> 
> if you want advice i think i commented everything with like // styles or something lol, but basically you probably need to up the array size for almost all the style variables or the max_styles variable and just do the same thing as the other styles but yeah gl

Thank you for the response, greatly appreciated. Most sourcepawn plugins are as old as the dinosaurs by tech standards so it was a breath of fresh air to find one updated this year and to have you respond is priceless. I'd love to help with the rewrite if you wanted to tackle that this year unfortunately I'd say only about half of the style related features are commented/stick out. I think I managed to find everything and add my own in except for those array variables so thank you for pointing those out. I will try again with a more simple style addition and let you know how that goes.

If you are interested in any of this or could spare a few minutes here and there to help me out I would greatly appreciate that **Discord**: `Mr. Full Moon#0001` promise I won't be too much of a bother @fluffyst ;)
