### ISSUE TITLE
Resetting stage information after spectating replay bot

### ISSUE THREAD

**Issue by Pintuzoft** [fluffyst/Surftimer#109]
Hi,

I found a minor bug where if you are on a staged map and you finish atleast the first stage, then spectate a replay bot to watch something, and then do !back. The stage information in the hud will now show you are on first stage rather than the stage you are located on. The time and actual location is retained and working fine, just that the stage information is reverted back to 1. This will cause an issue if you get stuck and/or otherwise use the !stuck command as it will then move you to the first stage rather than the stage you are located on.

The screenshot is of surf_classic2 stage 3 but is now after spectating the bot and typing !back showing it as stage 1. Am running version 2.2.

![classics2_stagebug](https://user-images.githubusercontent.com/6753348/51418232-96ba4900-1b82-11e9-98ea-16db2d168ba8.png)

**Comment by dPexxIAM** [comment]
https://github.com/maXusIprime/Surftimer/commit/483a46699d3746889ff4655cbb5113a320fc7044
