### ISSUE TITLE
Movement

### ISSUE THREAD

**Issue by SlightofHand** [fluffyst/Surftimer#11]
I don't know if this is a plugin problem or just csgo in general. 

Is there a way to fix mid air turning.. 
If a user turns to fast while in mid air the player just stops. (without crouch ofc). 
Maps like legends_lite and sundown (the walls) make turning corners at high speed very hard due to stopping most of the time. Wide turns work but adds more time to a run.

**Comment by fluffyst** [comment]
sv_airaccelerate
