### ISSUE TITLE
Crashing when player joins server

### ISSUE THREAD

**Issue by dagreek12** [fluffyst/Surftimer#119]
L 02/08/2019 - 22:12:10: [SM] Exception reported: Handle fa00f0 is invalid (error 3)
L 02/08/2019 - 22:12:10: [SM] Blaming: surftimer.smx
L 02/08/2019 - 22:12:10: [SM] Call stack trace:
L 02/08/2019 - 22:12:10: [SM]   [0] CloseHandle
L 02/08/2019 - 22:12:10: [SM]   [1] Line 1854, surftimer.sp::OnMapEnd
L 02/08/2019 - 22:12:10: Error log file session closed.
L 02/08/2019 - 22:12:11: SourceMod error session started
L 02/08/2019 - 22:12:11: Info (map "workshop/523356392/surf_prelude_ksf") (file "errors_20190208.log")
L 02/08/2019 - 22:12:11: [SM] Exception reported: Could not open file "c:\games\\csgo\csgo\addons\sourcemod\logs\surftimer\workshop\523356392\surf_prelude_ksf.log"
L 02/08/2019 - 22:12:11: [SM] Blaming: surftimer.smx
L 02/08/2019 - 22:12:11: [SM] Call stack trace:
L 02/08/2019 - 22:12:11: [SM]   [0] LogToFileEx
L 02/08/2019 - 22:12:11: [SM]   [1] Line 1672, surftimer.sp::OnMapStart

**Comment by totles** [comment]
this was fixed here: https://github.com/fluffyst/Surftimer/pull/112

just compile surftimer new or create the workshop and ID folder yourself for all your maps
