### ISSUE TITLE
rank bug after completion

### ISSUE THREAD

**Issue by maXusIprime** [fluffyst/Surftimer#12]
SurfTimer | Completed Stage 2 in 00:15:83 SR: +00:15:83 (Rank: #2/1)
how to fix this? :/

**Comment by fluffyst** [comment]
looks like two people got the same time

**Comment by maXusIprime** [comment]
i was the first to finish the stage. (SR: +00:15:83)

**Comment by fluffyst** [comment]
probably a bug when getting the first time on a stage then

**Comment by fluffyst** [comment]
Fixed with v2.0.1
