### ISSUE TITLE
What is stripper ?

### ISSUE THREAD

**Issue by abhishekdeshkar** [fluffyst/Surftimer#121]
Hello from India,

So I never hosted any surf server. This is the first time I'm hosting a surf server. I host PUG, Casual , retake etc servers. 

Anyway, I was going through Readme and I found this, "I have uploaded my stripper files here I have temporarily deleted this repo as I'm restarting my community, don't want the competiton to copy my server! Feel free to PM me for a download link though."

What is stripper ? And where can I get surf maps ? Also players are beginners so easy maps preferred.

Thanks a lot.

**Comment by stunslave** [comment]
Stripper:Source allows u to edit certain parts of maps without actually editing the map. Read up on it here. Not to difficult to use. ( [https://www.bailopan.net/stripper/](url) )

You can get maps from ( [https://gamebanana.com/](url) ) or another servers fastdl if its not locked. Maps are from tier 1 to 6, 1 being the easiest.

**Comment by abhishekdeshkar** [comment]
Thanks @fluffyst . Btw does this mod support Surf combat ?

**Comment by fluffyst** [comment]
I'm not sure why you would want to use a timer on combat surf
