### ISSUE TITLE
Just a Question - Rank Tags.

### ISSUE THREAD

**Issue by stunslave** [fluffyst/Surftimer#124]
Is there anyway to make different rank tags for each style?

So Normal would be:

Rank 1 - Wizardry
Rank 2-3 - Master
Rank 4-5 - Elite
etc

HSW Would be:

Rank 1 - HSW-God
Rank 2-3 - Legendary
Rank 4-5 - Pro
etc

**Comment by fluffyst** [comment]
nope, only way is to put {style} in the rank name
