### ISSUE TITLE
Issues and some ideas

### ISSUE THREAD

**Issue by czSMiLE** [fluffyst/Surftimer#13]
Issues : 
1) It attempts to download these files, but they are not even included here xd

/sound/surftimer/wr/1/valve_logo_music.mp3.

/sound/surftimer/wr/2/valve_logo_music.mp3.

/sound/surftimer/pr/valve_logo_music.mp3.

/sound/surftimer/top10/valve_logo_music.mp3 

2) I get no points for finishing maps. It just announce, that someone has completed map. (Doesn't show if he got points or not + nothing appear in database) Also name of player who finished map does never appear in database (here is just blank space). + doesn't even show finished maps. 

3) Custom titles doesn't work.

4) I wasn't able to change ranks in skillgroups.cfg . Nothing changes.

Ideas : 
1) I've noticed that here is config for server type (surf/bhop) . 0 = surf, 1 = bhop. So the idea -- automatically show "SYNC" in timer, if is server configured for bhop. It's very useful for bhop servers.

2) Country clantag in scoreboard

3) Block completly all other buttons in case someone change his style. For example -- Sideways. It's really annoying, that it resets everytime .

**Comment by fluffyst** [comment]
Issues:

1. fixed

2. Make sure the map has a tier, add one with sm_amt 0 tier

3. Works for me, tested it, make sure your custom title is enabled in sm_mytitle

4. Ranks are hard coded, that file does nothing

Ideas:
1. People can add it to the hud themselves

2. Fixed

3. Added as a cvar `ck_sideways_block_keys` default 0

**Comment by e-slut** [comment]
Nice!

**Comment by mloveless1227** [comment]
Why did you change the skillgroups to hard coded? What's the point of changing such a nice customization feature when there are so many other problems in ckSurf that need addressing?

**Comment by fluffyst** [comment]
Because I highly disagree with the percentage based system the original ckSurf uses and at the time it was easier to just hard code them the way I wanted it, I'll add something similar in the future, feel free to make a issue for what else needs addressing.
