### ISSUE TITLE
ckSurf overrides ALL Admin-Tag plugins

### ISSUE THREAD

**Issue by Sandman007** [fluffyst/Surftimer#14]
Hello,

First off I know this isn't your fault. This has been an issue since the original ckSurf plugin. But can you either completely remove the Admin tags function or change they way it handles tags?

Even when I set AdminTags to 0 in the cfg file, this plugin break compatibility with every AdminTags plugin out there that modifies tags in the scoreboard. I have tried even some very recent plugins on alliedmodders like these:

https://forums.alliedmods.net/showpost.php?p=2421587&postcount=61
https://forums.alliedmods.net/showthread.php?t=293563
https://forums.alliedmods.net/showthread.php?t=241345&page=5

All of these get overridden by ckSurf. You might see your custom tag from the above plugins for a like a split second when loading into the map but then ckSurf takes over.

Thanks!

**Comment by fluffyst** [comment]
This isn't just admin tags, it's because of that chat processing, however with this plugin it's possible for admins to set their "custom title" to "Admin" which will pretty much do the same thing as what you're asking.

**Comment by Sandman007** [comment]
Yes I am aware of that feature. But I like using a proper admin tag plugin because it's automatic. It's based of a flags and it forces my admins to wear their admin tags. Hence they can't unequip it.

It very bad to break other plugins for your own system. (Again I know this isn't your fault. It's been around since the start).

**Comment by fluffyst** [comment]
I can add this feature if you like, but changing the chat processing is a bit of a task considering how much the original ckSurf relies on it.

**Comment by Sandman007** [comment]
@fluffyst See the issue I made for Nikoo's plugin I made [here](https://github.com/nikooo777/ckSurf/issues/57#issuecomment-335042558). Seems someone has a fix!

**Comment by Sandman007** [comment]
@fluffust That solution would be great! I have a confession. I'm actually not using your timer currently. I'm using Nikoo's. But I was and still am planning to move to yours. 

As for the convar. I think it would be a nice addition. I Probably won't use it since I know some of my Admins prefer to show off their rank. 

Maybe if we can have that convar force the tag in the scoreboard but not in chat (so show player surf rank in chat) that would be nice. 

But you decide what you want.

**Comment by fluffyst** [comment]
If you wouldn't mind, I tried my own implementation of this feature, https://github.com/fluffyst/Surftimer/commit/62e7186eb40667fbb0a0d4f732c6c0d6447b7b93

https://github.com/fluffyst/Surftimer/tree/dev

Would help a lot if you tried it / bug tested it

**Comment by Sandman007** [comment]
@fluffyst Sure thing! I'll give it a test and let you know! It's 2am here and I have class/work in 6 hours so I'll have to do it tomorrow night. But I will def get back to you. 

Should I setup a fresh DB since I am using nikoo's plugin? I read somewhere you stated that a fresh DB is required but I figured that was if you were coming from 1.18?

**Comment by fluffyst** [comment]
You can use a existing database, just have to alter some tables, maybe i'll add a way to upgrade from niko to mine

**Comment by Sandman007** [comment]
@fluffyst Sure here you go!

[cksurf.zip](https://github.com/fluffyst/Surftimer/files/1371860/cksurf.zip)

**Comment by fluffyst** [comment]
Thanks ! Is this the latest version, v1.20?

**Comment by Sandman007** [comment]
@fluffyst yes it is.

**Comment by Sandman007** [comment]
@fluffyst Excellent! I read the commit. I will run the sql file and try out your plugin in a few hours.

**Comment by Sandman007** [comment]
Sorry I have been very busy the past week. I just performed the upgrade and while I couldn't do the testing myself today, I had an Admin confirm that the Timer is working as it should. I will do testing myself tomorrow. 

However my Mod told me that tags weren't working. I suspect since the are "default" tags they should just get them automatically if they have the appropriate flag? I am using Sbans to manage my Groups etc

`
"Default Titles"
{
  "0"
  {
    "flag" "z"
    "title" "{default}[{darkred}Owner{default}]"
  }
  "1"
  {
    "flag" "m"
    "title" "{default}[{green}Sr-Admin{default}]"
  }
  "2"
  {
    "flag" "f"
    "title" "{default}[{green}Admin{default}]"
  }
  "3"
  {
    "flag" "b"
    "title" "{default}[{green}Mod{default}]"
  }
  "4"
  {
    "flag" "a"
    "title" "{default}[{green}VIP{default}]"
  }
}
`

**Comment by fluffyst** [comment]
Is the ConVar `ck_enforce_default_titles` more than 0? it's 0 (disabled) by default

**Comment by Sandman007** [comment]
Yes it is. I just logged onto my server to check. First time I joined it just show "unranked" next to my name in the scoreboard. I rejoined it and it just says my name in the scoreboard and no tag.

**Comment by fluffyst** [comment]
Are you running the dev branch? Any errors?

**Comment by Sandman007** [comment]
Yep Dev branch. No errors that seemed related in the logs.

**Comment by fluffyst** [comment]
The latest smx? I tested it before and worked fine for me, make sure `ck_enforce_default_titles` isn't set to above 3 as well

**Comment by Sandman007** [comment]
I think I am using the latest smx but I will double check. I figured `ck_enforce_default_titles` would be a 0 or 1 value only?

**Comment by fluffyst** [comment]
has 3 values, 0 is disabled, 1 is only use the titles in the chat, 2 is only use the titles in the scoreboard, 3 is use the titles in both chat and scoreboard

**Comment by Sandman007** [comment]
Oh!!!! I am so stupid xD. So it was working but I had it set to show in chat only! I need to learn to read! The explanation was right there in the cfg file lol. 

I gotta say I am super pleased by this plugin already! Just the built in tags have made me super happy. Thanks @fluffyst! I guess I can close this now. You now have a new fan!

**Comment by fluffyst** [comment]
@Sandman007 I have changed the functionality in the latest commit, `ck_enforce_default_titles` is now 0/1 (disable/enable) and you can now change individual titles display in default_titles.txt with 
```
"type" "scoreboard"
"type" "chat"
"type" "both"
```

**Comment by Sandman007** [comment]
Got It! I'll grab the update tomorrow. Bed time for me now. :P
