### ISSUE TITLE
Start position bug

### ISSUE THREAD

**Issue by e-slut** [fluffyst/Surftimer#15]
When you set a new start position and spectate and restart while spectating it set's the start position at a random location usually outside the map but, if you join a team before you restart it's fine. I tested it on multiple maps and it does the same thing also tested it out on KP.

**Comment by fluffyst** [comment]
Can you try the new smx in the dev branch please, https://github.com/fluffyst/Surftimer/tree/dev

**Comment by e-slut** [comment]
Thanks! I'll test it out once I get home.

**Comment by e-slut** [comment]
Works!
