### ISSUE TITLE
pre-made zones ?

### ISSUE THREAD

**Issue by bedstespil** [fluffyst/Surftimer#16]
Hello.
Is it possible to get a maplist.txt and the option to get a package with all the maps in? As you have now made zones on?
In advance thank you.
Thanks for the new update :)

**Comment by fluffyst** [comment]
Not sure I understand, you want all the bsps and a maplist.txt with the maps in my premade zones?

**Comment by bedstespil** [comment]
Yes :-)

**Comment by fluffyst** [comment]
You can get the bsps from here http://fastdl.streamline-servers.com/fastdl/ThomasL1/13840/maps/ and https://pastebin.com/3R7c1Rq2

**Comment by bedstespil** [comment]
Hey. Do you have a fastdl link that works :-)?
In advance thank you.
