### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by Caaine** [fluffyst/Surftimer#17]
L 10/07/2017 - 16:21:22: [surftimer.smx] [Surftimer] SQL Error (sql_selectMapRecordCallback): Unknown column 'style' in 'field list'
L 10/07/2017 - 16:21:22: [surftimer.smx] [Surftimer] SQL Error (sql_selectPlayerProCountCallback): Unknown column 'style' in 'field list'
L 10/07/2017 - 16:21:23: [surftimer.smx] [Surftimer] SQL Error (db_selectMapCurrentImprovementCallback): Unknown column 'b.style' in 'where clause'
L 10/07/2017 - 16:21:29: [surftimer.smx] [Surftimer] SQL Error (SQL_selectPersonalRecordsCallback): Unknown column 'style' in 'field list'
L 10/07/2017 - 16:21:35: [surftimer.smx] [Surftimer] SQL Error (SQL_selectPersonalRecordsCallback): Unknown column 'style' in 'field list'
L 10/07/2017 - 16:21:51: [surftimer.smx] [Surftimer] SQL Error (SQL_selectPersonalRecordsCallback): Unknown column 'style' in 'field list'

Testing the Timer and this spamming my errorlog :<

**Comment by fluffyst** [comment]
Did you create tables with the create-table.sql file?

**Comment by Caaine** [comment]
yes :S can you accept my Friend request on Steam?
