### ISSUE TITLE
Quake sounds

### ISSUE THREAD

**Issue by RAMBATEN** [fluffyst/Surftimer#2]
Replay bot aint working for me...

I play with new smx the surf_ace...I stop in the stage like wall...

And how to enable quake sounds..

**Comment by fluffyst** [comment]
don't see why replay bot wouldn't work unless you didn't upload the nav file included in the maps folder.

stages have a speed cap in this timer, use sm_stageps #stage limit or sm_stageps 0 to unlimit all stages on the map

I'll upload the quake sounds

**Comment by fluffyst** [comment]
Actually, remembered I don't use quake sounds, they're included now so all you have to do is edit surftimer.sp and change the sound paths to whatever quake sound you want.

**Comment by RAMBATEN** [comment]
Thanks for the info
..I have uploaded the replay.botnav file..

**Comment by fluffyst** [comment]
you don't delete them you change the path to a quake sound file

it should create a surftimer.cfg automatically
