### ISSUE TITLE
DEV Branch

### ISSUE THREAD

**Issue by Caaine** [fluffyst/Surftimer#20]
L 10/10/2017 - 14:50:10: [SM] Exception reported: DataPack operation is out of bounds.
L 10/10/2017 - 14:50:10: [SM] Blaming: SurfTimer.smx
L 10/10/2017 - 14:50:10: [SM] Call stack trace:
L 10/10/2017 - 14:50:10: [SM]   [0] ReadPackCell
L 10/10/2017 - 14:50:10: [SM]   [1] Line 7040, surftimer/sql.sp::SQL_UpdateWrcpRecordCallback2

**Comment by aveniccii** [comment]
Same happens here.
Don't know what causes it.
Don't know what it affects.

**Comment by fluffyst** [comment]
Try the latest commit

**Comment by aveniccii** [comment]
Seems to have worked for me.

**Comment by fluffyst** [comment]
Did it spam the error or only once?

**Comment by aveniccii** [comment]
Nope, wasn't spamming for me.

**Comment by aveniccii** [comment]
Whoops, looks like I didn't test enough. Got the same error.

**Comment by fluffyst** [comment]
Has the line # changed?

**Comment by aveniccii** [comment]
L 10/11/2017 - 07:41:49: [SM]   [1] Line 7038, surftimer/sql.sp::SQL_UpdateWrcpRecordCallback2

**Comment by fluffyst** [comment]
try latest commit

**Comment by aveniccii** [comment]
Nope. Same error, same line.

**Comment by Caaine** [comment]
same error :D

**Comment by fluffyst** [comment]
try now

**Comment by guccigaming** [comment]
L 10/13/2017 - 19:56:52: [SM] Exception reported: DataPack operation is out of bounds.
L 10/13/2017 - 19:56:52: [SM] Blaming: SurfTimer.smx
L 10/13/2017 - 19:56:52: [SM] Call stack trace:
L 10/13/2017 - 19:56:52: [SM]   [0] ReadPackCell
L 10/13/2017 - 19:56:52: [SM]   [1] Line 7038, surftimer/sql.sp::SQL_UpdateWrcpRecordCallback2
L 10/13/2017 - 19:56:57: [SM] Exception reported: Array index is out of bounds
L 10/13/2017 - 19:56:57: [SM] Blaming: SurfTimer.smx
L 10/13/2017 - 19:56:57: [SM] Call stack trace:
L 10/13/2017 - 19:56:57: [SM]   [1] Line 7012, surftimer/sql.sp::SQL_UpdateWrcpRecordCallback


for me on the latest dev branch

**Comment by aveniccii** [comment]
L 10/13/2017 - 17:13:25: [SM] Exception reported: DataPack operation is out of bounds.
L 10/13/2017 - 17:13:25: [SM] Blaming: SurfTimer.smx
L 10/13/2017 - 17:13:25: [SM] Call stack trace:
L 10/13/2017 - 17:13:25: [SM]   [0] ReadPackCell
L 10/13/2017 - 17:13:25: [SM]   [1] Line 7038, surftimer/sql.sp::SQL_UpdateWrcpRecordCallback2

**Comment by fluffyst** [comment]
try the latest commit
