### ISSUE TITLE
[1] Line 411, surftimer/misc.sp::setClientLocation

### ISSUE THREAD

**Issue by bedstespil** [fluffyst/Surftimer#21]
L 10/10/2017 - 21:18:41: [SM] Exception reported: Array index is out of bounds
L 10/10/2017 - 21:18:41: [SM] Blaming: surftimer.smx
L 10/10/2017 - 21:18:41: [SM] Call stack trace:
L 10/10/2017 - 21:18:41: [SM]   [1] Line 411, surftimer/misc.sp::setClientLocation
L 10/10/2017 - 21:18:41: [SM]   [2] Line 136, surftimer/hooks.sp::Event_OnPlayerSpawn
L 10/10/2017 - 21:18:41: [SM]   [4] ChangeClientTeam
L 10/10/2017 - 21:18:41: [SM]   [5] Line 623, surftimer/misc.sp::TeamChangeActual
L 10/10/2017 - 21:18:41: [SM]   [6] Line 1187, surftimer/commands.sp::Command_JoinTeam

**Comment by fluffyst** [comment]
is this in the dev or master branch?

**Comment by bedstespil** [comment]
Surftimer-master

**Comment by fluffyst** [comment]
try that

**Comment by fluffyst** [comment]
Going to close this since there hasn't been a reply in a while, lmk if there's still a issue.
