### ISSUE TITLE
sm_customtitle does not apply title

### ISSUE THREAD

**Issue by bl4ckscor3** [fluffyst/Surftimer#26]
As the issue title says, the title set with "sm_customtitle newtitle" does not get applied. [This](https://i.imgur.com/LfjCgan.png) happens after executing the command.
We're using the version of the dev branch.

These are the default titles:
`"Default Titles"
{
  "z"
  {
    "title" "{default}[{darkred}Owner{default}]"
  }
  "e"
  {
    "title" "{default}[{darkblue}Head Admin{default}]"
  }
  "b"
  {
    "title" "{default}[{green}Admin{default}]"
  }
}
`

**Comment by fluffyst** [comment]
try `sm_mytitle` and making sure your custom title is enabled

**Comment by bl4ckscor3** [comment]
According to the menu, it is enabled. However [in chat](https://i.imgur.com/HTMVv3S.png), I cannot see the title.

**Comment by fluffyst** [comment]
what's the value of `ck_enforce_default_titles` , works fine for me when set to 0 which is intended

**Comment by bl4ckscor3** [comment]
Ah, that was an oversight. It was set to 3, we changed it and the titles are working now.

**Comment by bl4ckscor3** [comment]
Is there a possibility to add an option to show custom titles regardless of that option? Like a per-player override for ck_enforce_default_titles that said player could toggle.

**Comment by fluffyst** [comment]
so, a steamid whitelist perhaps?

**Comment by bl4ckscor3** [comment]
Exactly. Let's say ck_enforce_default_titles is to 3, but an admin wants a custom title. He would then be able to go to sm_mytitle and enable his custom title so it can show instead despite ck_enforce_default_titles being set to 3.

**Comment by fluffyst** [comment]
that would defeat the purpose of the titles being "enforced" though, I could add a whitelist section to the default_titles.txt file however, not sure if that's tedious to have to add every admin that you want to be able to use custom titles to the txt file though
