### ISSUE TITLE
sm_gb/sm_goback unintended behavior

### ISSUE THREAD

**Issue by bl4ckscor3** [fluffyst/Surftimer#27]
If the map timer is deactivated, the command sets you back to the stage you're currently in. If the map timer is running, you'll be set back to the start zone (beginning of the map).
Intended behavior is that you go back a stage (if you are in stage 3, you go to stage 2, etc.).

We also had an instance, were a player would get teleported to stage 3 from stage 7, however we did not find a cause or way of reproducing this specific error.

**Comment by fluffyst** [comment]
try the new commit
