### ISSUE TITLE
Hide Admin Commands from Help Menu and fixbot

### ISSUE THREAD

**Issue by Caaine** [fluffyst/Surftimer#28]
sm_help menu has been revamped and will now automatically add any command with [surftimer] in the description.

can you make [vip] and [admin] or [mapmakers]
to hide comamands in the Help menu for normal user?

can you make this cvar only Admin?
sm_fixbot

user can spam this command

**Comment by fluffyst** [comment]
try the latest commit

**Comment by Caaine** [comment]
I have no Admin rights
#latest commit

https://i.imgur.com/aMG6oIz.png
