### ISSUE TITLE
Unable to load plugin "SurfTimer.smx"

### ISSUE THREAD

**Issue by 5H4D0W5T4LK3R** [fluffyst/Surftimer#29]
L 10/13/2017 - 14:26:49: [SM] Unable to load plugin "SurfTimer.smx": Native "json_array_append_new" was not found

This is the full error I get with the new surftimer.smx update. The previous version gave no errors whatsoever, any ideas?

Regards

**Comment by fluffyst** [comment]
hm, try uploading this https://forums.alliedmods.net/showthread.php?t=184604

**Comment by 5H4D0W5T4LK3R** [comment]
v2.00 The master version I guess, download it from here. Meaning the surftimer.smx version before the 5 days ago update.

I installed it now, and the next thing it gives me is this

[SM] Plugin surftimer.smx failed to load: Native "DiscordWebHook.Send" was not found.

**Comment by Caaine** [comment]
Requirements

    Sourcemod 1.8
    MySQL (SQLite may work but is not supported by me)
    DHooks (Included)
    The following dependencies are required for the discord functionality, I will make these things optional in the future, sorry
    Sourcemod-Discord (Included)
    SteamWorks
    SMJansson

**Comment by fluffyst** [comment]
Yeah, install discord_api.smx from the new plugins folder

**Comment by 5H4D0W5T4LK3R** [comment]
discord_api.smx is installed on the server, along with steamworks, still give me that error.

Why would I need to install this now even tho it did work previously without?

**Comment by fluffyst** [comment]
The old version didn't have the discord functionality

**Comment by 5H4D0W5T4LK3R** [comment]
Makes sense, well the discord_api plugin is installed, and steamworks is on there as well. Yet I still get this
[SM] Plugin surftimer.smx failed to load: Native "DiscordWebHook.Send" was not found.

**Comment by fluffyst** [comment]
hm, you get that error when discord_api fails to load, have you restarted the server after installing those things?

**Comment by 5H4D0W5T4LK3R** [comment]
So here's the sequence, I installed discord_api, steamworks and smjansson. Restarted the server, joined it, noticed that there's no timer + bots running around, tried to manually load surftimer.smx through rcon then it returns with the "DiscordWebHook.Send" error.

**Comment by fluffyst** [comment]
can you upload the file `addons/sourcemod/logs/errors_date.log`

**Comment by 5H4D0W5T4LK3R** [comment]
[errors_20171013.log.txt](https://github.com/fluffyst/Surftimer/files/1382903/errors_20171013.log.txt)

**Comment by 5H4D0W5T4LK3R** [comment]
That's the log that was created just now, date being the 13th atm geo location might differ that much?

**Comment by fluffyst** [comment]
ah, yeah it's 12am where I am, okay so the issue is you don't have SteamWorks installed

**Comment by 5H4D0W5T4LK3R** [comment]
Seems to have worked, updating the datbase, everything running smooth now. 

Thanks
