### ISSUE TITLE
Adding vip/super vip

### ISSUE THREAD

**Issue by Steezy63** [fluffyst/Surftimer#3]
Hey,

how can i add vip's/super vip's?

**Comment by fluffyst** [comment]
I initially was doing it via sourcebans, so the timer doesn't actually have a way to add someone as vip, you can add them through a mysql insert into the ck_vipadmins table and give them a vip value of 1/2/3 though

**Comment by Steezy63** [comment]
Hey,
its still not working i tried adding myself and gave me a VIP rank but that didnt change anything. Here a screen oft my db

https://gyazo.com/cecac820087369afd1182c9845a26c7c
