### ISSUE TITLE
Points not working

### ISSUE THREAD

**Issue by 5H4D0W5T4LK3R** [fluffyst/Surftimer#30]
After finishing a map, you aren't awarded with points. Mapname is in mapcycle, point system is on in the options. Runs and times do get saved to database, but aren't awarded any points

**Comment by fluffyst** [comment]
have you added a tier to the map?

**Comment by 5H4D0W5T4LK3R** [comment]
Thought they were pre added, but seems like adding the tier works to some of the maps that aren't on the list. 
Thanks again

**Comment by fluffyst** [comment]
they're pre added if yo used the `optional/ck_maptier.sql` file
