### ISSUE TITLE
Replay bots

### ISSUE THREAD

**Issue by Kovacc** [fluffyst/Surftimer#32]
It would be nice if you could add a replay bot system like the one on Marco's fork. It's kind of annoying waiting for the bot to cycle through the stages until it gets to the stage you want to see. I also would like to be able to watch styled records as well. I know it's quite a big task but I think it's a great feature to have in the timer. Thanks!

**Comment by Cruze03** [comment]
+1 would be pretty nice!

**Comment by fluffyst** [comment]
This feature has been added `sm_replay`
