### ISSUE TITLE
sm_showzones doesn't save state when reconnecting/changing map

### ISSUE THREAD

**Issue by bl4ckscor3** [fluffyst/Surftimer#34]
If you activate `sm_showzones` and change the map or reconnect to the server, the zones will no longer show. This can be annoying if you want to zone multiple maps after each other.

**Comment by fluffyst** [comment]
intended, so players don't lag the server by having showzones on all the time, you don't need to turn on showzones to edit zones either, that might only be in the dev branch though, can't remember
