### ISSUE TITLE
Custom join message doesn't allow for spaces

### ISSUE THREAD

**Issue by bl4ckscor3** [fluffyst/Surftimer#37]
If setting a custom join message via `sm_joinmsg` only the characters up until the first space will be used. Example: `sm_joinmsg This is a join message` will yield `This` as a join message instead of `This is a join message`

**Comment by fluffyst** [comment]
Put the join msg in quotes `sm_joinmsg "this is a join message"`

**Comment by bl4ckscor3** [comment]
I see. Unintuitive at first glance, but makes sense.
