### ISSUE TITLE
Suggestion for style mrank commands

### ISSUE THREAD

**Issue by bl4ckscor3** [fluffyst/Surftimer#38]
It would be nice to have commands for all styles, that act the same as `sm_mrank`. For instance, `sm_hswmrank` would show your local map rank of the hsw style.

**Comment by SlightofHand** [comment]
What would be better is to have a separate ranking system for hsw / backwards / sideways.. Basically they rank the same as normal, you get points for each listed style but the points add to each of their own style...

So if !top is typed it will show

1. Normal top 10
2. Normal Map top 10
3. Hsw top 10
4. Hsw Map top 10
5. Backwards top 10
6. Backwards Map top 10
7. etc

and each sub menu for each style will be

Example HSW

HSW top 10

1. Soh - 203994 points
2. Fishy - 19990 points
3. Soul - 14890 points
4. etc 

Now that would be nice :>

**Comment by fluffyst** [comment]
The issue with what you suggested is how big the menu's are going to be, also mrank is a entirely different command that doesn't use a menu, I did evenutally plan to give styles their own ranking system but styles aren't rly big in surf, don't think anyone honestly cares about them, people who surf HSW use binds, so it's not really a priority

**Comment by SlightofHand** [comment]
K i understand (people use binds for everything its a fact, if it's easier people will use it, same with turn binds or autobhop). 

How about just a HSW replay bot :> (since like 40% of players play HSW) Or is there another plugin that has hsw bots?

**Comment by fluffyst** [comment]
Added
