### ISSUE TITLE
Native "surftimer_ClientIsVIP" was not found

### ISSUE THREAD

**Issue by Caaine** [fluffyst/Surftimer#39]
if( CheckCommandAccess( client, "+paint", ADMFLAG_GENERIC, true) || surftimer_ClientIsVIP(client))

Unable to load plugin "paint.smx": Native "surftimer_ClientIsVIP" was not found

can you add the native? surftimer_ClientIsVIP

**Comment by fluffyst** [comment]
`surftimer_IsClientVip`
