### ISSUE TITLE
How do you give VIP to somebody ? (or any other title)

### ISSUE THREAD

**Issue by bobytza** [fluffyst/Surftimer#4]
It seems like sm_giveadmintitle doesn't work anymore, is there a new command ?

**Comment by fluffyst** [comment]
[https://github.com/fluffyst/Surftimer/issues/3](url)

**Comment by bobytza** [comment]
Yea but "csgo\addons\sourcemod\configs\ckSurf\custom_chat_titles.txt" can't be used anymore, am I right ?

**Comment by fluffyst** [comment]
correct
