### ISSUE TITLE
[CS:GO] Error with new Sourcemod Version [Linux]

### ISSUE THREAD

**Issue by ZeitZumKiffen** [fluffyst/Surftimer#41]
Hey, thanks too Update the Script but i have alot of errors, the error logs say this here:

`L 10/18/2017 - 10:49:34: SourceMod error session started
L 10/18/2017 - 10:49:34: Info (map "surf_deoa") (file "errors_20171018.log")
L 10/18/2017 - 10:49:34: [SM] Unable to load extension "cleaner.ext": Failed to find signature. Please contact the author.
L 10/18/2017 - 10:49:34: [SM] Unable to load plugin "discord_api.smx": Native "SteamWorks_CreateHTTPRequest" was not found
L 10/18/2017 - 10:49:34: [SM] Unable to load plugin "surftimer.smx": Native "DiscordWebHook.Send" was not found`

i install SteamWorks, SMJansson and the Cleaner (https://forums.alliedmods.net/showthread.php?t=195008) 

i hope the topic is okay, i dont found a any forum with your updatet ckSurf script :) i hope someone can say me the error

**Comment by fluffyst** [comment]
you don't have steamworks installed `Native "SteamWorks_CreateHTTPRequest" was not found`

http://users.alliedmods.net/~kyles/builds/SteamWorks/

**Comment by ZeitZumKiffen** [comment]
I install a old version (fuck) and thank you for the new version of steamworks

the last error is: 
L 10/18/2017 - 12:05:08: [SM] Unable to load extension "cleaner.ext": Failed to find signature. Please contact the author.

I use the "cleaner.ext.2.csgo.so" version, i think the cleaner.ext is for css ?

**Comment by fluffyst** [comment]
try the cleaner in the dev branch, it's been updated https://github.com/fluffyst/Surftimer/tree/dev/addons/sourcemod/extensions

**Comment by ZeitZumKiffen** [comment]
perfect, thank you for all :) and sorry for the noob question :D
