### ISSUE TITLE
Error while zoning 

### ISSUE THREAD

**Issue by Steezy63** [fluffyst/Surftimer#42]
L 10/30/2017 - 14:24:06: [SM] Exception reported: Array index is out of bounds
L 10/30/2017 - 14:24:06: [SM] Blaming: surftimer.smx
L 10/30/2017 - 14:24:06: [SM] Call stack trace:
L 10/30/2017 - 14:24:06: [SM]   [1] Line 1831, surftimer/surfzones.sp::EditorMenu
L 10/30/2017 - 14:24:06: [SM]   [2] Line 1866, surftimer/surfzones.sp::MenuHandler_Editor

Dev Branch

**Comment by fluffyst** [comment]
try the latest commit

**Comment by Steezy63** [comment]
fixed....thanks :)
