### ISSUE TITLE
CreateNavFile crash

### ISSUE THREAD

**Issue by maXusIprime** [fluffyst/Surftimer#43]
https://github.com/nikooo777/ckSurf/pull/61

so you don't forget about it ;)

**Comment by fluffyst** [comment]
haven't tested but should work, if theirs does

**Comment by maXusIprime** [comment]
Works fine so far. You only forgot to make `CreateNavFiles();` -> `//CreateNavFiles();` in SurfTimer.sp

**Comment by fluffyst** [comment]
and I forgot to compile lol, thanks =)
