### ISSUE TITLE
DEFAULT CHARSET=utf8mb4

### ISSUE THREAD

**Issue by Caaine** [fluffyst/Surftimer#45]
changed my mysql to utf8mb4
https://i.imgur.com/a78jpJx.png
https://i.imgur.com/f0YQ4Tb.png

error.log
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DEFAULT CHARSET=utf8mb4' at line 1

**Comment by fluffyst** [comment]
https://stackoverflow.com/questions/34690195/getting-errors-when-converting-to-utf8mb4-unicode-ci
