### ISSUE TITLE
mapchooser

### ISSUE THREAD

**Issue by SlightofHand** [fluffyst/Surftimer#46]
!nominate doesn't show any maps just the tiers. 
The database isn't getting any information.. 

Is there meant to be a .sql file to upload to the db to make tables or anything?

**Comment by fluffyst** [comment]
should make this issue in the mapchooser repo, any errors?

**Comment by SlightofHand** [comment]
L 11/01/2017 - 14:49:15: [nominations.smx] [Nominations] SQL Error (SelectCompletedMapsCallback): Table 'csgo-2017-mapchooser.ck_playertimes' doesn't exist
L 11/01/2017 - 14:49:16: [nominations.smx] [Nominations] SQL Error (SelectIncompleteMapsCallback): Table 'csgo-2017-mapchooser.ck_zones' doesn't exist

**Comment by SlightofHand** [comment]
we might know whats wrong - I didnt create the db.

**Comment by fluffyst** [comment]
the database needs to be the same as the timers database

**Comment by SlightofHand** [comment]
okay kewl thanks!
