### ISSUE TITLE
Replay bot issues

### ISSUE THREAD

**Issue by k0r4y** [fluffyst/Surftimer#47]
Sometimes bots for the WR, BWR and WRCP spawn with their default bot names and not the replay bot name, they also just stand still instead of showing the replay. Using the !fixbot command fixes it sometimes, sometimes the command will break a correct bot by turning the bot that was working fine (for example the WR bot) into a default bot, but then the WRB bot starts working fine. 

This issue was also present in ckSurf 1.8 and 1.9 iirc.

Not sure what the cause for this is as there are no messages in the console reflecting anything related to the bots.

**Comment by SlightofHand** [comment]
Ye same things happens on our servers. Windows server. (its always been like this even on old cksurf timer)

**Comment by guccigaming** [comment]
ubuntu 16.04 LTS

**Comment by fluffyst** [comment]
hm, I always thought it was OS specific but apparently not. 

@SlightofHand how can you have 3 bots in the old timer though? Isn't there only a map and bonus bot?

**Comment by SlightofHand** [comment]
there's a information bot also.

**Comment by SlightofHand** [comment]
Well u can set the bot on and off in /ckadmin menu in the old timer.

**Comment by fluffyst** [comment]
Ah yeah, forgot about the info bot, I'll see if I can find any solutions

**Comment by fluffyst** [comment]
Perhaps try the dev branch now? I didn't really change anything in terms of loading bots, but on my test server (Windows) all 3 bots were loading fine.
