### ISSUE TITLE
Error @hookzones 

### ISSUE THREAD

**Issue by Steezy63** [fluffyst/Surftimer#48]
L 11/02/2017 - 00:03:13: [SM] Exception reported: Entity 93 (93) is invalid
L 11/02/2017 - 00:03:13: [SM] Blaming: surftimer.smx
L 11/02/2017 - 00:03:13: [SM] Call stack trace:
L 11/02/2017 - 00:03:13: [SM]   [0] GetEntPropVector
L 11/02/2017 - 00:03:13: [SM]   [1] Line 764, surftimer/surfzones.sp::BeamBox_OnPlayerRunCmd
L 11/02/2017 - 00:03:13: [SM]   [2] Line 1165, surftimer/hooks.sp::OnPlayerRunCmd

L 11/02/2017 - 00:26:22: Info (map "surf_delta") (file "errors_20171102.log")
L 11/02/2017 - 00:26:22: [SM] Exception reported: Array index is out of bounds
L 11/02/2017 - 00:26:22: [SM] Blaming: surftimer.smx
L 11/02/2017 - 00:26:22: [SM] Call stack trace:
L 11/02/2017 - 00:26:22: [SM]   [1] Line 412, surftimer/misc.sp::setClientLocation
L 11/02/2017 - 00:26:22: [SM]   [2] Line 166, surftimer/hooks.sp::Event_OnPlayerSpawn
L 11/02/2017 - 00:26:22: [SM]   [4] ChangeClientTeam
L 11/02/2017 - 00:26:22: [SM]   [5] Line 624, surftimer/misc.sp::TeamChangeActual
L 11/02/2017 - 00:26:22: [SM]   [6] Line 1471, surftimer/commands.sp::Command_JoinTeam
L 11/02/2017 - 00:26:40: [SM] Exception reported: Array index is out of bounds
L 11/02/2017 - 00:26:40: [SM] Blaming: surftimer.smx
L 11/02/2017 - 00:26:40: [SM] Call stack trace:
L 11/02/2017 - 00:26:40: [SM]   [1] Line 412, surftimer/misc.sp::setClientLocation
L 11/02/2017 - 00:26:40: [SM]   [2] Line 398, surftimer/misc.sp::teleportEntitySafe
L 11/02/2017 - 00:26:40: [SM]   [3] Line 4642, surftimer/commands.sp::HookZoneHandler

Last Dev Branch

**Comment by fluffyst** [comment]
should be fixed in the next commit

**Comment by Steezy63** [comment]
Nice :) 

I think you forgotten the colors in hooks.sp line 750 & 758

**Comment by fluffyst** [comment]
hm, the line number has changed for me since i've changed stuff in hooks.sp, what function is it in?

**Comment by Steezy63** [comment]
PrintToChat(client, "%cSurftimer %c| | You may not jump in this area."); 
&
PrintToChat(client, "%cSurftimer %c| | You may not crouch in this area.");
