### ISSUE TITLE
Custom Title color doesn't work

### ISSUE THREAD

**Issue by bobytza** [fluffyst/Surftimer#5]
Regardless textcolour/namecolour in db, title and name show white in game.
STEAMID | TITLE | namecolour | textcolour | inuse | vip | admin | zoner
STEAMID | OWNER | 1 | 1 | 1 | 3 | 1 | 0

**Comment by fluffyst** [comment]
does the title actually show?

**Comment by bobytza** [comment]
Yes, but in white same as the name regardless of the colour I chose in VIP menu.

**Comment by fluffyst** [comment]
is ck_colored_chatnames set to 1?

**Comment by bobytza** [comment]
Yea, now it works. Sorry for retarded questions.
