### ISSUE TITLE
Still Errors @hookzones

### ISSUE THREAD

**Issue by Steezy63** [fluffyst/Surftimer#51]
L 11/02/2017 - 02:13:44: Info (map "surf_delta") (file "errors_20171102.log")
L 11/02/2017 - 02:13:44: [SM] Exception reported: Array index is out of bounds
L 11/02/2017 - 02:13:44: [SM] Blaming: surftimer.smx
L 11/02/2017 - 02:13:44: [SM] Call stack trace:
L 11/02/2017 - 02:13:44: [SM]   [1] Line 412, surftimer/misc.sp::setClientLocation
L 11/02/2017 - 02:13:44: [SM]   [2] Line 166, surftimer/hooks.sp::Event_OnPlayerSpawn
L 11/02/2017 - 02:13:44: [SM]   [4] ChangeClientTeam
L 11/02/2017 - 02:13:44: [SM]   [5] Line 624, surftimer/misc.sp::TeamChangeActual
L 11/02/2017 - 02:13:44: [SM]   [6] Line 1471, surftimer/commands.sp::Command_JoinTeam

L 11/02/2017 - 15:23:19: Info (map "surf_jaqen2") (file "errors_20171102.log")
L 11/02/2017 - 15:23:19: [SM] Exception reported: Menu handle c8ec0177 is invalid (error 3)
L 11/02/2017 - 15:23:19: [SM] Blaming: surftimer.smx
L 11/02/2017 - 15:23:19: [SM] Call stack trace:
L 11/02/2017 - 15:23:19: [SM]   [0] DisplayMenu
L 11/02/2017 - 15:23:19: [SM]   [1] Line 4589, surftimer/commands.sp::HookZonesMenu
L 11/02/2017 - 15:23:19: [SM]   [2] Line 4565, surftimer/commands.sp::Command_HookZones
L 11/02/2017 - 15:23:22: [SM] Exception reported: Menu handle c8ec0177 is invalid (error 3)
L 11/02/2017 - 15:23:22: [SM] Blaming: surftimer.smx
L 11/02/2017 - 15:23:22: [SM] Call stack trace:
L 11/02/2017 - 15:23:22: [SM]   [0] DisplayMenu
L 11/02/2017 - 15:23:22: [SM]   [1] Line 4589, surftimer/commands.sp::HookZonesMenu
L 11/02/2017 - 15:23:22: [SM]   [2] Line 4565, surftimer/commands.sp::Command_HookZones

**Comment by fluffyst** [comment]
Do people who make their own issues not have the option to re-open? Maybe I shouldn't close until confirmed then, my bad, will look into this!

**Comment by Steezy63** [comment]
Nope, can't re-open. 
surf_delta -> Teleport to Zone doenst work 
surf_jaqen2 -> Set Start Hookzone and try to set end hookzone (Hookzones menu doesnt open)

**Comment by fluffyst** [comment]
try this commit, teleport to zone on surf_delta worked fine for me though

**Comment by Steezy63** [comment]
Still got some errors, menu shows up now but after i set start hookzone i can't set a map end hookzone ...If i press 2 the menu disappears

surf_delta still broken for me :( 

Full Errorlog: https://gyazo.com/fdd4855b51ddd729f6d2df43365881cd
