### ISSUE TITLE
zones

### ISSUE THREAD

**Issue by SlightofHand** [fluffyst/Surftimer#55]
We stop when bhopping on stages when not in a zone. Says (Surftimer | You may only jump once inside this zone) But we are not in the zone.

Cant create a speed zone, we dont have the option.. We have hook zone, but in all menu's there is no speed zone. (sm_sps does not work anymore) (tried changing to hook didnt do anything other than being able to see all sides of the zone, start zone.) or i don't know what exactly it does.

![untitled 1](https://user-images.githubusercontent.com/31367393/32417516-a43ed376-c263-11e7-99eb-da0de74e4d69.jpg)
![Uploading Untitled 2.jpg…]()
![untitled 3](https://user-images.githubusercontent.com/31367393/32417518-a494a774-c263-11e7-8458-a084b5ed166e.jpg)

Sometimes stage records save with random times... Like say i did a stage in 7sec it would save the record as 2sec, making it impossible to beat. The replay stays as the correct time. Very random stuff.

Is there some command I am missing :P

**Comment by maXusIprime** [comment]
If you want to change the speed of the zone just go !zones -> Edit zones -> select the zone and then you can change the speed

**Comment by SlightofHand** [comment]
there's no speed zone. Edit zones/normal map zones/start-0/set zone type and it shows start/end/stage/hook zone ... There's no speed zone.

**Comment by SlightofHand** [comment]
o i see thanks.

**Comment by fluffyst** [comment]
Yes, speed zones have been removed, instead make a start zone and set the prespeed to 0 or unlimit, there's also the option to disable the one jump limit
