### ISSUE TITLE
Custom Titles.

### ISSUE THREAD

**Issue by SlightofHand** [fluffyst/Surftimer#61]
Was wondering if there was a way to use custom_chat_titles.txt in config/surftimer. (i know this does not work anymore)
A way that we could set pre made titles that if set by using a users "steam id" that user can select from a list of titles which they can use. (like old cksurf)

Before I think it was something like sm_givetitle "nickname" and we could select which titles we wanted to give to that user, like Admin / mod / Other surf names or w.e, and then he could choose out of those titles which he would like to use or just the default tag. (basically a menu instead of allowing one extra title by using command /title /customtitle)

**Comment by fluffyst** [comment]
default_titles serves this purpose

**Comment by SlightofHand** [comment]
ye, but is there a way for the user to change between the given tag (admin) and his default tag, or will the users always have to use (admin) as his tag. 

Is there no way to switch between 2/3 different tags? Without having the choice of choosing their own tags.

**Comment by fluffyst** [comment]
no, but if you want a admin to be able to use different tags, why not just make them set their custom title to "admin", it does the same thing, then they're able to change it, can't really see any downside to allowing them to freely change their title if they want to switch between some predetermined ones

**Comment by SlightofHand** [comment]
Ye, but its not for admins. That was just a example tag, its for a group of players. They will use [iNt] and would like to move between [iNt] and their default point tag. I see that it's not possible.
Thanks for your time. I'll try figure something out.
