### ISSUE TITLE
L 11/14/2017 - 20:19:41: [surftimer.smx] [Surftimer] SQL Error (SQL_selectMapZonesCallback): Unknown column 'hookname' in 'field list'

### ISSUE THREAD

**Issue by bedstespil** [fluffyst/Surftimer#62]
L 11/14/2017 - 20:19:41: [surftimer.smx] [Surftimer] SQL Error (SQL_selectMapZonesCallback): Unknown column 'hookname' in 'field list'

(Master) Surftimer.

**Comment by bedstespil** [comment]
ck_maptier.sql / ck_zones.sql

I get the error after I have put these two files into the database.

**Comment by fluffyst** [comment]
you sure you imported ck_zones.sql? the column definitely gets created https://github.com/fluffyst/Surftimer/blob/master/optional/ck_zones.sql#L17
