### ISSUE TITLE
SQL_ViewPlayerInfoCallback on windows 

### ISSUE THREAD

**Issue by Steezy63** [fluffyst/Surftimer#63]
<del>> L 11/15/2017 - 16:34:40: SourceMod error session started
L 11/15/2017 - 16:34:40: Info (map "surf_me") (file "errors_20171115.log")
L 11/15/2017 - 16:34:40: [SM] Exception reported: Native is not bound
L 11/15/2017 - 16:34:40: [SM] Blaming: surftimer.smx
L 11/15/2017 - 16:34:40: [SM] Call stack trace:
L 11/15/2017 - 16:34:40: [SM]   [1] SourceComms_SetClientGag
L 11/15/2017 - 16:34:40: [SM]   [2] Line 4744, surftimer/commands.sp::CommsVoteHandle </del>

<del> I think it was !votegag </del> FiXED

> L 11/15/2017 - 17:49:07: Info (map "surf_beginner") (file "errors_20171115.log")
L 11/15/2017 - 17:49:07: [SM] Exception reported: Invalid time format or buffer too small
L 11/15/2017 - 17:49:07: [SM] Blaming: surftimer.smx
L 11/15/2017 - 17:49:07: [SM] Call stack trace:
L 11/15/2017 - 17:49:07: [SM]   [0] FormatTime
L 11/15/2017 - 17:49:07: [SM]   [1] Line 33, surftimer/sqltime.sp::SQL_ViewPlayerInfoCallback
L 11/15/2017 - 19:03:21: Error log file session closed. 

!profile ->Player -> Player info 

<del>> L 11/15/2017 - 16:38:45: [surftimer.smx] [Surftimer] SQL Error (sql_selectTopBonusSurfersCallback): Column 'style' in where clause is ambiguous </del> 

FiXED

<del> > L 11/15/2017 - 23:54:35: Info (map "surf_kitsune2_go") (file "errors_20171115.log")
L 11/15/2017 - 23:54:35: [SM] Exception reported: Array index is out of bounds
L 11/15/2017 - 23:54:35: [SM] Blaming: surftimer.smx
L 11/15/2017 - 23:54:35: [SM] Call stack trace:
L 11/15/2017 - 23:54:35: [SM]   [1] Line 357, surftimer/hooks.sp::Say_Hook </del>

<del> can't disable one jump limit in edit zones </del> comes only if you type nothing in chat at target name

**Comment by fluffyst** [comment]
Hey, so I decided to just remove the votegag/votemute commands as they rely on sourcebans++ and they were made specifically for KP anyway, probably other plugins that do the same thing.

Will fix the player info soon, for some reason only works on Linux currently.

Fixed `L 11/15/2017 - 16:38:45: [surftimer.smx] [Surftimer] SQL Error (sql_selectTopBonusSurfersCallback): Column 'style' in where clause is ambiguous`

That last error isn't related to the one jump limit, it's to do with changing the targetName of a zone, I tried both disabling/enabling one jump limit and changing the targetname, both on a start zone and they worked fine, mind telling me what map and which zone?

**Comment by Steezy63** [comment]
I will test it when i'm at home :) 

Mmh i think it was a stage zone on kitsune2_go... was a misclick on target Player :D

**Comment by Steezy63** [comment]
yea it's the target name in stage zones when you write nothing in chat...if you write reset in chat there's  no error 

surf_kitsune2_go disable one jump on s2-12 doesnt save the settings after map reload ...After map reload it is enabled

**Comment by fluffyst** [comment]
so everything is working?

**Comment by Steezy63** [comment]
i think so ...dunno what i made wrong at one jump limit sry :x 

updated title and first post .... you can close it if you want

**Comment by fluffyst** [comment]
Hey, just committed a fix for player info not working on windows servers, try it out please!

**Comment by Steezy63** [comment]
Nice, fixed :) thanks for your hard work <3
