### ISSUE TITLE
Translation string formatted incorrectly

### ISSUE THREAD

**Issue by Caaine** [fluffyst/Surftimer#64]
L 11/17/2017 - 14:47:38: [SM] Exception reported: Translation string formatted incorrectly - missing at least 1 parameters
L 11/17/2017 - 14:47:38: [SM] Blaming: SurfTimer.smx
L 11/17/2017 - 14:47:38: [SM] Call stack trace:
L 11/17/2017 - 14:47:38: [SM]   [0] VFormat
L 11/17/2017 - 14:47:38: [SM]   [1] Line 195, colorvariables.inc::CReplyToCommand
L 11/17/2017 - 14:47:38: [SM]   [2] Line 245, mapsettings.sp::Command_SetGravityFix

**Comment by fluffyst** [comment]
try latest commit
