### ISSUE TITLE
Default Titles Issue

### ISSUE THREAD

**Issue by Cruze03** [fluffyst/Surftimer#65]
First of all, Thank you so much for this... Everything works very well for me leaving that mentioned below. 

The thing that doesn't work is default titles.. no tags are shown for any flags or steamid. Just normal rank tag is shown.

**Comment by fluffyst** [comment]
make sure `ck_enforce_default_titles` is set to 1

**Comment by Cruze03** [comment]
Yes, it is set to 1.

**Comment by fluffyst** [comment]
paste your default_titles.txt file

**Comment by Cruze03** [comment]
https://pastebin.com/4vh1GrBd
Nothing much changed just the steamid tag.

**Comment by fluffyst** [comment]
hm, any errors in `addons/sourcemod/logs/errors_date.log`? last time I checked default titles was working
