### ISSUE TITLE
wrcp points

### ISSUE THREAD

**Issue by SlightofHand** [fluffyst/Surftimer#66]
// Wrcp Points
g_hWrcpPoints = CreateConVar("ck_wrcp_points", "0", "Sets the amount of points a player should get for a WRCP, 0 to disable");

I have set this to 15 and added sm_cvar ck_wrcp_points 15 to server.cfg (i did recompile the plugin).

Am i missing something it doesn't seem to work.

**Comment by fluffyst** [comment]
it doesn't recalculate your points on stage finish, try getting a wrcp then manually refresh your profile, should see a 15 point increase
