### ISSUE TITLE
!bonustop and speedstart zones and some other small bugs

### ISSUE THREAD

**Issue by guccigaming** [fluffyst/Surftimer#7]
The different style times are all listed under !bonustop without any way to differentiate the times based on the styles. If you use the fastforward style and on a bonus it's very easy to appear as rank 1 on !bonustop.

Speedstart zones still block you at 350 speed, you have to change the allowed prespreed in the database, not sure if this is working as intended?

!bonusinfo is pretty wonky too.

Chat announcements about stage records sometimes give out wrong information, like wrong stage, but the information is saved correctly if you check it on !wrcp.

Thanks for publishing your fork of ckSurf, all the players on my server really enjoy the changes!

**Comment by fluffyst** [comment]
speedstart zones are pretty much useless, just use normal start zones and change the prespeed with sm_sps.
sm_bonusinfo was broken in normal cksurf, don't believe there's even a way to add a tier to bonuses anyway (not that they need them)
The wrong stage msg happens when there is multiple end zones

**Comment by guccigaming** [comment]
Thank you for responding so quickly with an answer to the prespeed issue!
sm_amt 1 <tier> adds the bonus tier and I'll keep the wrong stage msg in mind.

**Comment by fluffyst** [comment]
yea i know it adds the bonus tier but it's never displayed the correct tier, even in ckSurf, if I remember correctly I think he messed up the formatting though, I just never bothered to fix it.

bonus top needs `AND style = 0` added to the SQL query

**Comment by fluffyst** [comment]
Fixed in version 2.0.1
