### ISSUE TITLE
!top

### ISSUE THREAD

**Issue by SlightofHand** [fluffyst/Surftimer#71]
if we use !top and choose hsw really anything other than normal and go to the top map times (in hsw menu). It gives the normal map top times and not hsw map top times. Is meant to be like this or is it broken?

Top Menu - Half-Sideways

1. Top 100 (shows hsw top players)
2. Map top (shows normal map top times)
3. Bonus (haven't tested bonus)

**Comment by SlightofHand** [comment]
Also is there anyway to change the prefix from [surftimer] to something else? That would be nice addition to this plugin. (its not a big deal but would be nice)

**Comment by fluffyst** [comment]
I'll fix the top issue next update.
There is a cvar to change the prefix, ck_chat_prefix maybe?
Yes, that is also a cvar.
No, but surf_goliath isn't a tier 7

**Comment by SlightofHand** [comment]
k thanks. 

I thought surf_trofle , surf_pyrism and surf_goliath was, o well looks like ksf is changing tiers to their surf lvl again :>

**Comment by fluffyst** [comment]
Re-opening so I don't forget to fix the !top issue!

**Comment by fluffyst** [comment]
Should be fixed now!
