### ISSUE TITLE
SurfTimer | Max bhops exceeded (Limit 4)

### ISSUE THREAD

**Issue by bedstespil** [fluffyst/Surftimer#8]
Hello. How do I turn this off?
Can not find it in any config file.
I use a plugin on bhop server, so it must be turned off.
Thanks in advance :)

**Comment by fluffyst** [comment]
can't remember if this version has the convar or not, try ck_bhop_limit 0

**Comment by bedstespil** [comment]
It does not work. Has changed it in file and made a new upload.

**Comment by fluffyst** [comment]
you need to compile the plugin and upload the smx

**Comment by bedstespil** [comment]
//// SurfTimer.sp
//
// SurfTimer/misc.sp(2384) : warning 204: symbol is assigned a value that is never used: "index"
// SurfTimer/misc.sp(2488) : warning 217: loose indentation
// SurfTimer/misc.sp(2520) : warning 217: loose indentation
// SurfTimer/commands.sp(1015) : warning 217: loose indentation
// SurfTimer/commands.sp(1796) : warning 204: symbol is assigned a value that is never used: "szMenuTitle"
// SurfTimer/commands.sp(1910) : warning 217: loose indentation
// SurfTimer/commands.sp(1911) : warning 217: loose indentation
// SurfTimer/commands.sp(3494) : warning 213: tag mismatch
// SurfTimer/hooks.sp(1018) : error 010: invalid function or declaration
// SurfTimer/sql.sp(863) : warning 204: symbol is assigned a value that is never used: "totalplayers"
// SurfTimer/sql.sp(1020) : warning 204: symbol is assigned a value that is never used: "rank"
// SurfTimer/sql.sp(1019) : warning 204: symbol is assigned a value that is never used: "totalplayers"
// SurfTimer/sql.sp(1183) : warning 203: symbol is never used: "top10"
// SurfTimer/sql.sp(1182) : warning 203: symbol is never used: "wr"
// SurfTimer/sql.sp(9433) : warning 217: loose indentation
// SurfTimer/sql.sp(9434) : warning 217: loose indentation
// SurfTimer/sql.sp(9470) : warning 217: loose indentation
// SurfTimer/sql.sp(9472) : warning 217: loose indentation
// SurfTimer/sql.sp(9567) : warning 203: symbol is never used: "points"
// SurfTimer/draw.sp(100) : warning 203: symbol is never used: "entity"
// SurfTimer.sp(2491) : warning 213: tag mismatch
// SurfTimer.sp(2527) : error 017: undefined symbol "Event_PlayerJump"
// SurfTimer.sp(7118) : warning 204: symbol is assigned a value that is never used: "g_bLoadingWrcpSettings"
//
// 2 Errors.
//
// Compilation Time: 3,89 sec
// ----------------------------------------

**Comment by fluffyst** [comment]
did you remove the entire event? i guess you could do that too but you need to remove it from surftimer.sp line 2527 too, not sure what line 1018 in hooks.sp is now since you removed the event_playerjump

**Comment by fluffyst** [comment]
Removed with version 2.0.1
