### ISSUE TITLE
unable to load surftimer.smx

### ISSUE THREAD

**Issue by Osher12** [fluffyst/Surftimer#80]
L 01/06/2018 - 22:34:36: [SM] Unable to load plugin "discord_api.smx": Required extension "SteamWorks" file("SteamWorks.ext") not running
L 01/06/2018 - 22:34:36: [SM] Unable to load plugin "smjansson.test.smx": Required extension "SMJansson" file("smjansson.ext") not running
L 01/06/2018 - 22:34:36: [SM] Unable to load plugin "surftimer.smx": Native "json_array_append_new" was not found

**Comment by fluffyst** [comment]
install steamworks and smjanson
