### ISSUE TITLE
Bonus timer doesn't start unless teleporting to bonus start zone

### ISSUE THREAD

**Issue by M-archand** [fluffyst/Surftimer#83]
If I walk to a bonus start from a main run start zone, the bonus timer won't start. It doesn't matter if your start timer is still going or if it was stopped using a trigger. The only way I can seem to get a bonus run to start is if I tele to it using `!b 1` or what have you, then it's fine.

I'm new to this fork of the plugin so I apologize if I'm misguided but I couldn't find any cfg settings relating to this

**Comment by fluffyst** [comment]
This is intended, kind of. It was the only way I could make a maps start zone and a bonus start zone sitting on top of each other work, I assumed there aren't many surf maps where people can even get to the bonus manually or people who would bother.

**Comment by M-archand** [comment]
Fair enough. However there's plenty, but the only instance I can think of a bonus sitting on top of a start is surf_trance_ksf. 

One of the first questions I got after switching to this plugin was "why won't the bonus timers start" D:
