### ISSUE TITLE
Rank issue (always given highest rank)

### ISSUE THREAD

**Issue by M-archand** [fluffyst/Surftimer#84]
I've tried using "rank", "points" and "percentage" configurations and no matter what I do all user are given the same highest rank title, despite not being a high enough rank or having enough points for it. I tried recalculating ranks etc.

I converted from Niko's version, is there something I missed?

Here's an example: 
![image](https://user-images.githubusercontent.com/13469995/37432648-cd1f2a48-27b7-11e8-9dbb-244e4a6ad907.png)

**Comment by SlightofHand** [comment]
Your skillgroups.cfg should look like this:
Don't use percentage it's quite inaccurate.

"SkillGroups"
{
	"1"
	{
		"rankTitle" "{default}[{lime}{style}{darkred}Wiza{green}rdry{default}]"
		"nameColour" "{lime}"
		"rank" "1-2"
	}
	"2"
	{
		"rankTitle" "{default}[{blue}{style}{pink}GodLike{default}]"
		"nameColour" "{green}"
		"rank" "3-4"
	}
	"3"
	{
		"rankTitle" "[{lime}{style}Legendary]"
		"nameColour" "{darkred}"
		"points" "270000-9999999"
	}
	"4"
	{
		"rankTitle" "{pink}[{style}Master]"
		"nameColour" "{blue}"
		"points" "200000-269999"
	}
	"5"
	{
		"rankTitle" "{red}[{style}Elite]"
		"nameColour" "{purple}"
		"points" "140000-199999"
	}
	"6"
	{
		"rankTitle" "{lime}[{style}Veteran]"
		"nameColour" "{lightred}"
		"points" "90000-149999"
	}
	"7"
	{
		"rankTitle" "{purple}[{style}Expert]"
		"nameColour" "{green}"
		"points" "50000-89999"
	}
	"8"
	{
		"rankTitle" "{lime}[{style}Pro]"
		"nameColour" "{purple}"
		"points" "24000-49999"
	}
	"9"
	{
		"rankTitle" "{orange}[{style}Hardcore]"
		"nameColour" "{purple}"
		"points" "15000-23999"
	}
	"10"
	{
		"rankTitle" "{yellow}[{style}Buttery]"
		"nameColour" "{orange}"
		"points" "10000-14999"
	}
	"11"
	{
		"rankTitle" "{lightgreen}[{style}Hotshot]"
		"nameColour" "{lightgreen}"
		"points" "7000-9999"
	}
	"12"
	{
		"rankTitle" "{darkblue}[{style}Experienced]"
		"nameColour" "{darkblue}"
		"points" "5000-6999"
	}
	"13"
	{
		"rankTitle" "{blue}[{style}Skilled]"
		"nameColour" "{blue}"
		"points" "3600-4999"
	}
	"14"
	{
		"rankTitle" "{lightblue}[{style}Casual]"
		"nameColour" "{lightblue}"
		"points" "1800-3599"
	}
	"15"
	{
		"rankTitle" "{gray2}[{style}Beginner]"
		"nameColour" "{gray2}"
		"points" "1000-1799"
	}
	"16"
	{
		"rankTitle" "{gray}[{style}Rookie]"
		"nameColour" "{gray}"
		"points" "500-999"
	}
	"17"
	{
		"rankTitle" "{default}[{style}Pleb]"
		"nameColour" "{default}"
		"points" "0"
	}
}

I had the same problem previously and it was because my skill group ranks were in the incorrect order. The above is correct.

**Comment by fluffyst** [comment]
Above is correct, but in the original post, the screenshot only has 3 skillgroups with points in the correct order, I tried to replicate myself with what's in the original post but it worked fine for me.
