### ISSUE TITLE
sm_vip

### ISSUE THREAD

**Issue by SlightofHand** [fluffyst/Surftimer#9]
I have been trying to get **sm_vip** working on my db, but for some reason I can only get one of the users steam ID to work, tried to change the id's a couple of times but nothing has worked. I'm using the **STEAM_1:X:xxx** ID.

I tried to override the command in **admin_overrides.cfg** (This did not work either)

**Comment by fluffyst** [comment]
that's the correct id, is there a error or what does it say to the player?

**Comment by SlightofHand** [comment]
Just says they don't have access to the command. I have tried all vip flags (1 = vip, 2 = super vip, 3 = bdc)

**Comment by fluffyst** [comment]
remove the admin_overrides, the plugin doesn't give them any fags, just set their vip lvl to at least 1 and it should work, the error should say `"You must be a VIP to use this feature %chttps://ztsgaming.com.au/Donate"` if they don't meet the VIP requirement

**Comment by SlightofHand** [comment]
Ye I have removed the overrides, I have tried all vip lvl's I have left it set to 3. (The steam id's could be causing the problem) or that's the only thing I think it could be.

I removed the working id replaced it with others and tried them non worked, Re-added the working id and tested it again and it worked.. Very random stuff.

Image of DB: http://imgur.com/a/RZBxJ

**Comment by fluffyst** [comment]
ah, my bad, the check is `if (g_iVipLvl[client] < 1 && g_iAdminLvl[client] < 1)` either change it to `if (g_iVipLvl[client] < 1 || g_iAdminLvl[client] < 1)` or give them a admin lvl of 1

**Comment by SlightofHand** [comment]
Changed the code didn't work, also tried to give admin lvl 1 it did not work either. It's weird that it's working for one id but non of the others.

**Comment by fluffyst** [comment]
did you compile and upload the smx?

**Comment by SlightofHand** [comment]
Yes I did recompile and copy over the new plugin + scripting.

**Comment by fluffyst** [comment]
you don't need to upload scripting, doesn't do anything.

do you perhaps have another plugin that uses sm_vip as a command? because it looks fine to me, list your sm plugins list

**Comment by SlightofHand** [comment]
"Admin File Reader" (1.8.0.6017) by AlliedModders LLC
 "SQL Admins (Prefetch)" (1.8.0.5997) by AlliedModders LLC
 "Admin Help" (1.8.0.6017) by AlliedModders LLC
 "Admin Menu" (1.8.0.6017) by AlliedModders LLC
 "Advertisements" (2.0.2) by Tsunami
 "AFK Manager" (4.1.5) by Rothgar
 "Anti-Flood" (1.8.0.6017) by AlliedModders LLC
 "Basic Ban Commands" (1.8.0.6017) by AlliedModders LLC
 "Basic Chat" (1.8.0.6017) by AlliedModders LLC
 "Basic Comm Control" (1.8.0.6017) by AlliedModders LLC
 "Basic Commands" (1.8.0.6017) by AlliedModders LLC
 "Basic Info Triggers" (1.8.0.6017) by AlliedModders LLC
 "Basic Votes" (1.8.0.6017) by AlliedModders LLC
 "CallAdmin" (0.1.5) by Impact, Popoklopsi
 "CallAdmin: Mysql module" (0.1.5) by Impact, Popoklopsi
 "CallAdmin: Steam module" (0.1.5) by Impact, Popoklopsi
 "CallAdmin UserManager" (0.1.5) by Popoklopsi, Impact
 "[Any] Chat Logging Redux + RTF Support" (1.1.2) by McFlurry, Keith Warren (Drixevel)
 "Client Preferences" (1.8.0.6017) by AlliedModders LLC
 "CS:GO Movement Unlocker" (1.0) by Peace-Maker
 "Disable Radar" (1.2) by Internet Bully
 "Fun Commands" (1.8.0.6017) by AlliedModders LLC
 "Fun Votes" (1.8.0.6017) by AlliedModders LLC
 "joinrestartproblem.smx" joinrestartproblem.smx
 "Nextmap" (1.8.0.6017) by AlliedModders LLC
 "NoBlock" (1.0) by fluxX
 "No Fall Damage" (0.0.1.9) by alexip121093
 "Player Commands" (1.8.0.6017) by AlliedModders LLC
 "Reserved Slots" (1.8.0.6017) by AlliedModders LLC
 "Rules Plugin" (1.1) by haN
 "SimpleCSGOAntiAFK" (0.0.8) by Puppetmaster
 "Slope Landing Fix" (1.2) by Mev & Blacky
 "[SM] Admins Online (Sorted List)" (1.0.0) by Grey83
 "Sound Commands" (1.8.0.6017) by AlliedModders LLC
 "SQL Admin Manager" (1.8.0.6017) by AlliedModders LLC
 "SuperLogs: Generic" (1.0) by psychonic
 "TempBan" (1.0.0) by bl4nk
 "[UMC] Admin Menu" (3.4.6-dev) by Steell
 "[UMC] Ultimate Mapchooser Core" (3.4.6-dev) by Steell
 "[UMC] Echo Nextmap" (3.4.6-dev) by Steell
 "[UMC] End of Map Vote Warnings" (3.4.6-dev) by Steell
 "[UMC] End of Map Vote" (3.4.6-dev) by Steell
 "[UMC] Extend and Don't Change Positioning" (3.4.6-dev) by Steell
 "[UMC] Map Commands" (3.4.6-dev) by Steell
 "[UMC] Nominations" (3.4.6-dev) by Steell
 "[UMC] Player Count Monitor" (3.4.6-dev) by Steell
 "[UMC] Player Limits" (3.4.6-dev) by Steell
 "[UMC] Post-Played Exclusion" (3.4.6-dev) by Sazpaimon and Steell
 "[UMC] Prefix Exclusion" (3.4.6-dev) by Steell
 "[UMC] Random Cycle" (3.4.6-dev) by Steell
 "[UMC] Rock The Vote" (3.4.6-dev) by Steell
 "[UMC] Time Limits" (3.4.6-dev) by Steell
 "[UMC] Vote Command" (3.4.6-dev) by Steell
 "[UMC] Map Weight" (3.4.6-dev) by Steell
 "WannabeDJ" (1.0) by Gary
 "SurfTimer" (2.05) by Fluffys, Jakeey802

**Comment by fluffyst** [comment]
i don't see any that have a vip command, maybe wannabedj? idk, sm_vip isn't registered as a admin command so it shouldn't be giving the you do not have access message, i'll maybe re-write the vip part of the plugin because it's probably buggy since I ripped out the sourcebans dependency

**Comment by SlightofHand** [comment]
Thanks for your help. 
I will try a few other things to see if I can get it to work, if not I'll just leave it as is for now.
