### ISSUE TITLE
Highlight the start point for each surf map

### ISSUE THREAD

**Issue by jljr222** [fluffyst/Surftimer#91]
I was using another custom ckSurf build and it had a cool effect of putting a border around the start area. Could we add something similar to Surftimer? It could be a CVAR if people do not want it on their server. I think it's helpful.

**Comment by dPexxIAM** [comment]
// 0 = Do not display zones, 1 = display the lower edges of zones, 2 = display whole zones
// -
// Default: "0"
ck_zone_drawstyle "0"

in surftimer.cfg

**Comment by jljr222** [comment]
Welp, I'm just bad at configs. Thanks though @dPexxIAM !
