### ISSUE TITLE
Gravity Bug

### ISSUE THREAD

**Issue by M-archand** [fluffyst/Surftimer#99]
Been having issues with gravity. After hitting the boosts gravity doesn't go away/reset. I searched through Discord and tried a couple things but nothing works. Gravityfix is set to 1.  Works fine after disabling the plugin. Don't have any other movement/boost/gravity plugins running.

Example: 

surf_cubic stage 8, boost launches you faster than normal and gravity doesn't stop, you get stuck in the air - 
![giphy1](https://user-images.githubusercontent.com/13469995/41881953-a36184a2-78bc-11e8-95ba-97bd5f8157c0.gif)

surf_colors_final_d stage 7, gravity doesn't reset after hitting the low gravity area, once you jump you're low grav again - 
![giphy2](https://user-images.githubusercontent.com/13469995/41882095-4a325aae-78bd-11e8-83d8-320e2af4669c.gif)

**Comment by cRUSHER-HLG** [comment]
dynamically change it by !ms. So you can set for maps if they are enabled or not,

**Comment by M-archand** [comment]
Indeed, the fix is to set 'gravityfix' to 0 in ck_maptier.

**Comment by cRUSHER-HLG** [comment]
Exactly that what i sayed. with !ms you change the gravity ingame and dont need to go into db.

**Comment by kmsraidboss** [comment]
This still seems to be an issue in the latest builds. I've attempted turning gravity fix on and off via configs, !ms, and even directly in the DB for maps. Any low gravity area on any map sends players right to the ceiling and the maps are unplayable. 

Are there any legitimate fixes out there? Even upgrades to this plugin that someone is selling?
